export const ISBLACKTHEME = "ISBLACKTHEME";

// Create account actions
export const SET_NAME_IN_CREATE_ACCOUNT = "SET_NAME_IN_CREATE_ACCOUNT";
export const SET_PASSWORD_IN_CREATE_ACCOUNT = "SET_PASSWORD_IN_CREATE_ACCOUNT";
export const SET_SEED_IN_CREATE_ACCOUNT = "SET_SEED_IN_CREATE_ACCOUNT";
export const SET_PINCODE_IN_CREATE_ACCOUNT = "SET_PINCODE_IN_CREATE_ACCOUNT";
