export const ISBLACKTHEME = "ISBLACKTHEME";
export const SET_CURRENT_ACCOUNT = "SET_CURRENT_ACCOUNT";
export const SET_ENTRY_ROUTE = "SET_ENTRY_ROUTE";
export const SET_CURRENT_PRICE= "SET_CURRENT_PRICE";
