export const ISBLACKTHEME = "ISBLACKTHEME";
export const SET_CURRENT_ACCOUNT = "SET_CURRENT_ACCOUNT";
export const SET_ENTRY_ROUTE = "SET_ENTRY_ROUTE";
export const SET_WALLET_ROUTE = "SET_WALLET_ROUTE";
export const SET_CURRENT_PRICE= "SET_CURRENT_PRICE";


// Wallet Routes
export const WALLET_ROUTE_ASSETS= "WALLET_ROUTE_ASSETS";
export const WALLET_ROUTE_NFTS= "WALLET_ROUTE_NFTS";
export const WALLET_ROUTE_TRANSACTIONS= "WALLET_ROUTE_TRANSACTIONS";
