export const ERROR_ACCOUNT = {
  DERIVE_ERROR: 'DERIVE_ERROR',
  WRONG_PASSWORD: 'WRONG_PASSWORD',
  ACCOUNT_ALREADY_EXISTS: 'ACCOUNT_ALREADY_EXISTS',
  ACCOUNT_NAME_ALREADY_EXISTS: 'ACCOUNT_NAME_ALREADY_EXISTS',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  INVALID_ADDRESS: 'INVALID_ADDRESS',
  NOT_ENOUGH_BALANCE: 'NOT_ENOUGH_BALANCE',
  NOT_ENOUGH_AMOUNT: 'NOT_ENOUGH_AMOUNT',
  ACCOUNT_CAN_NOT_HOLD_ASSET_WITHOUT_ADA:
    'ACCOUNT_CAN_NOT_HOLD_ASSET_WITHOUT_ADA',
};
export const ERROR_TRANSACTION = {
  BUILDER_ERROR: 'BUILDER_ERROR',
  TX_ADD_OUTPUT_ERROR: 'TX_ADD_OUTPUT_ERROR',
  TX_NO_ASSETS_WITHOUT_ADA: 'TX_NO_ASSETS_WITHOUT_ADA',
  TX_NO_ENOUGH_ADAS_FOR_ASSETS: 'TX_NO_ENOUGH_ADAS_FOR_ASSETS',
  TX_NO_ENOUGH_ADAS: 'TX_NO_ENOUGH_ADAS',
  TX_NO_ENOUGH_ADA_FOR_MINIMUM_VALUE: 'TX_NO_ENOUGH_ADA_FOR_MINIMUM_VALUE',
};
