export const ENTRY_WITCH_ROUTE = {
    HOME_PAGE: 'ENTRY_WITCH_ROUTE_HOME_PAGE',
    WELCOME: 'ENTRY_WITCH_ROUTE_WELCOME',
    LANGUAGE: 'ENTRY_WITCH_ROUTE_LANGUAGE',
    LOCK_PAGE: 'ENTRY_WITCH_LOCK_PAGE',
    LOADING_PAGE: 'ENTRY_WITCH_LOADING_PAGE',
    UPDATE_ENTRY_WITCH_ROUTE: "UPDATE_ENTRY_WITCH_ROUTE"
};
